### PR TITLE
Compile against openssl 3

### PR DESCRIPTION
**Pull request by traversaro**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Comment by traversaro** [comment]
It is not using the correct openssl:
~~~
-- Found OpenSSL: optimized;D:/bld/libpcap_1683109473806/_h_env/Library/lib/libcrypto.lib;debug;C:/Program Files/OpenSSL/lib/VC/libcrypto64MDd.lib (found version "1.1.1t")  
~~~

**Comment by traversaro** [comment]
> It is not using the correct openssl:
> 
> ```
> -- Found OpenSSL: optimized;D:/bld/libpcap_1683109473806/_h_env/Library/lib/libcrypto.lib;debug;C:/Program Files/OpenSSL/lib/VC/libcrypto64MDd.lib (found version "1.1.1t")  
> ```

No, actually it is the correct one for the `optimized` build, it is founding something else for the `debug` library, but that should not be a problem as we are doing a Release build, that is using `optimized` libraries.

**Comment by traversaro** [comment]
~@conda-forge/libpcap @nehaljwani The PR is ready for review, thanks!~ Actually not, for some reason the PR did not re-render.

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Comment by traversaro** [comment]
The error is:
~~~
[21/78] Building C object CMakeFiles\pcap.dir\pcap-rpcap.c.obj
FAILED: CMakeFiles/pcap.dir/pcap-rpcap.c.obj 
C:\PROGRA~1\MICROS~2\2022\ENTERP~1\VC\Tools\MSVC\1429~1.301\bin\HostX64\x64\cl.exe  /nologo -DBUILDING_PCAP -DHAVE_CONFIG_H -DYY_NO_UNISTD_H -D_CRT_SECURE_NO_WARNINGS -D__STDC__ -Dpcap_EXPORTS -I%SRC_DIR%\build -I%SRC_DIR% -external:I%PREFIX%\Library\include -external:W0 /DWIN32 /D_WINDOWS /W3 /MT /O2 /Ob2 /DNDEBUG  /utf-8 -wd4646 /showIncludes /FoCMakeFiles\pcap.dir\pcap-rpcap.c.obj /FdCMakeFiles\pcap.dir\ /FS -c %SRC_DIR%\pcap-rpcap.c
%PREFIX%\Library\include\openssl/ssl.h(1973): error C2146: syntax error: missing ')' before identifier 'offset'
%PREFIX%\Library\include\openssl/ssl.h(1973): error C2081: 'off_t': name in formal parameter list illegal
%PREFIX%\Library\include\openssl/ssl.h(1973): error C2061: syntax error: identifier 'offset'
%PREFIX%\Library\include\openssl/ssl.h(1973): error C2059: syntax error: ';'
%PREFIX%\Library\include\openssl/ssl.h(1973): error C2059: syntax error: ','
%PREFIX%\Library\include\openssl/ssl.h(1974): error C2059: syntax error: ')'
%PREFIX%\Library\include\openssl/ssl.h(1973): error C2059: syntax error: ';'
%PREFIX%\Library\include\openssl/ssl.h(1973): error C2059: syntax error: ','
%PREFIX%\Library\include\openssl/ssl.h(1974): error C2059: syntax error: ')'
ninja: build stopped: subcommand failed.
~~~

That is familiar as I had already discussed it in https://github.com/conda-forge/libpcap-feedstock/pull/14 .

**Comment by traversaro** [comment]
> The error is:
> 
> ```
> [21/78] Building C object CMakeFiles\pcap.dir\pcap-rpcap.c.obj
> FAILED: CMakeFiles/pcap.dir/pcap-rpcap.c.obj 
> C:\PROGRA~1\MICROS~2\2022\ENTERP~1\VC\Tools\MSVC\1429~1.301\bin\HostX64\x64\cl.exe  /nologo -DBUILDING_PCAP -DHAVE_CONFIG_H -DYY_NO_UNISTD_H -D_CRT_SECURE_NO_WARNINGS -D__STDC__ -Dpcap_EXPORTS -I%SRC_DIR%\build -I%SRC_DIR% -external:I%PREFIX%\Library\include -external:W0 /DWIN32 /D_WINDOWS /W3 /MT /O2 /Ob2 /DNDEBUG  /utf-8 -wd4646 /showIncludes /FoCMakeFiles\pcap.dir\pcap-rpcap.c.obj /FdCMakeFiles\pcap.dir\ /FS -c %SRC_DIR%\pcap-rpcap.c
> %PREFIX%\Library\include\openssl/ssl.h(1973): error C2146: syntax error: missing ')' before identifier 'offset'
> %PREFIX%\Library\include\openssl/ssl.h(1973): error C2081: 'off_t': name in formal parameter list illegal
> %PREFIX%\Library\include\openssl/ssl.h(1973): error C2061: syntax error: identifier 'offset'
> %PREFIX%\Library\include\openssl/ssl.h(1973): error C2059: syntax error: ';'
> %PREFIX%\Library\include\openssl/ssl.h(1973): error C2059: syntax error: ','
> %PREFIX%\Library\include\openssl/ssl.h(1974): error C2059: syntax error: ')'
> %PREFIX%\Library\include\openssl/ssl.h(1973): error C2059: syntax error: ';'
> %PREFIX%\Library\include\openssl/ssl.h(1973): error C2059: syntax error: ','
> %PREFIX%\Library\include\openssl/ssl.h(1974): error C2059: syntax error: ')'
> ninja: build stopped: subcommand failed.
> ```
> 
> That is familiar as I had already discussed it in #14 .

Indeed, the issue was the one described in https://github.com/openssl/openssl/issues/18310 . While the proper solution is for openssl to avoid exposing in headers functions that are not on Windows, the problem that we had specifically in pcap is that `off_t` is not defined by Windows UCRT headers under certain conditions, that apparently are verified in the pcap build. Anyhow, to define `off_t` it is sufficient to define the `_CRT_DECLARE_NONSTDC_NAMES` macro, see https://learn.microsoft.com/en-us/cpp/c-runtime-library/compatibility?view=msvc-170 . So, in https://github.com/conda-forge/libpcap-feedstock/pull/18/commits/331f347cae812d082916cb301042c041220112d1 we just added a macro that did exactly that, and now the build is green. @conda-forge/libpcap @nehaljwani the PR is ready for review, for real this time.

**Comment by nehaljwani** [comment]
Could you please update the build matrix to build for both versions of openssl?

**Comment by traversaro** [comment]
> Could you please update the build matrix to build for both versions of openssl?

Do you have any specific motivation for this? conda-forge stopped supporting openssl 1.* once it completed the openssl3 migration (see https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/3892). Continuing to compile again openssl 1.* can work for some time, but at some point it can break once there is some ABI migration or similar that will not occur for openssl 1.* .

**Comment by nehaljwani** [comment]
Ah, I didn't know that. Thanks, merging.

**Comment by traversaro** [comment]
> Ah, I didn't know that. Thanks, merging.

Perfect, thanks!

**Pull request merged**
